/**
 * Pointing your other tools at ModelDock.
 *
 * Three verbs and a strict order: `GET` computes what would change, `POST
 * /apply` writes it, `POST /revert` takes it back out. Nothing is written by a
 * GET, and `apply` recomputes the plan server-side rather than trusting a body
 * — so what lands is what this server decided, not what a request claimed.
 *
 * This is also where the gateway's token is handed to the page, and it is the
 * only route that returns it. That is a deliberate and narrow exception to the
 * rule that credentials never cross this boundary: the token is *generated by*
 * ModelDock rather than belonging to a provider, it is worthless off this
 * machine, and the whole point of the feature is showing someone the value they
 * need to paste. The rule that matters — that provider API keys never leave the
 * server — is untouched.
 */

import { Hono } from "hono";

import { servingPort } from "../config.js";
import { db } from "../db/index.js";
import { HttpError } from "../errors.js";
import { gatewayCatalog } from "../gateway/catalog.js";
import { gatewayToken, gatewayTokenPath, rotateGatewayToken } from "../gateway/token.js";
import { HANDOFFS, HANDOFF_LIST, type HandoffKind } from "../handoff/catalog.js";
import { applyHandoff, revertHandoff } from "../handoff/apply.js";
import { gatewayOrigin, planHandoff } from "../handoff/plan.js";

export const handoffRoutes = new Hono();

function kindFrom(value: string | undefined): HandoffKind {
  if (value && value in HANDOFFS) return value as HandoffKind;
  throw new HttpError(404, `ModelDock does not know how to set up "${value}".`);
}

/**
 * Everything the screen needs in one call.
 *
 * The catalogue is computed once and passed into both plans rather than being
 * fetched per tool — it is four network round trips, and doing it twice to
 * render one panel would be plainly wasteful.
 */
handoffRoutes.get("/handoff", async (c) => {
  const database = db();
  const port = servingPort();
  const catalog = await gatewayCatalog(database);

  const plans = await Promise.all(
    HANDOFF_LIST.map((spec) => planHandoff(database, spec.kind, port, catalog)),
  );

  return c.json({
    gateway: {
      origin: gatewayOrigin(port),
      /** What each protocol's clients should be given. Both are shown. */
      openaiBaseUrl: `${gatewayOrigin(port)}/v1`,
      anthropicBaseUrl: gatewayOrigin(port),
      token: gatewayToken(),
      tokenPath: gatewayTokenPath(),
      modelCount: catalog.models.length,
      problems: catalog.problems,
      models: catalog.models.map((model) => ({
        id: model.id,
        connection: model.connectionName,
        label: model.label,
      })),
    },
    targets: plans,
  });
});

handoffRoutes.post("/handoff/:kind/apply", async (c) => {
  const kind = kindFrom(c.req.param("kind"));
  const result = await applyHandoff(db(), kind, servingPort());
  return c.json(result);
});

handoffRoutes.post("/handoff/:kind/revert", async (c) => {
  const kind = kindFrom(c.req.param("kind"));
  const result = await revertHandoff(db(), kind, servingPort());
  return c.json(result);
});

/**
 * Mint a new token.
 *
 * Every config file carrying the old one stops working, which is why this is a
 * deliberate action and why the response says how many targets need re-applying
 * rather than quietly leaving them broken.
 */
handoffRoutes.post("/handoff/rotate", async (c) => {
  const token = rotateGatewayToken();
  const database = db();
  const port = servingPort();

  const plans = await Promise.all(
    HANDOFF_LIST.map((spec) => planHandoff(database, spec.kind, port)),
  );

  return c.json({
    token,
    stale: plans.filter((plan) => plan.exists && !plan.applied).map((plan) => plan.label),
  });
});
